const planets = [
  {
    id: 1,
    name: "Mercury",
    type: "Terrestrial",
    category: "Planet",
    moons: [
      {
        id: 1.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 1.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 1.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 1.4,
        name: "Moon 4",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 1.5,
        name: "Moon 5",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 1.6,
        name: "Moon 6",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      }
    ],
  },
  {
    id: 2,
    name: "Venus",
    type: "Terrestrial",
    category: "Planet",
    moons: [
      {
        id: 2.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 2.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 2.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 2.4,
        name: "Moon 4",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 2.5,
        name: "Moon 5",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 2.6,
        name: "Moon 6",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      }
    ],
  },
  {
    id: 3,
    name: "Earth",
    type: "Terrestrial",
    category: "Planet",
    moons: [
      {
        id: 3.1,
        name: "The Moon",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      }
    ],
  },
  {
    id: 4,
    name: "Mars",
    type: "Terrestrial",
    category: "Planet",
    moons: [
      {
        id: 4.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 4.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 4.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
    ],
  },
  {
    id: 5,
    name: "Jupiter",
    type: "Gas Giant",
    category: "Planet",
    moons: [
      {
        id: 5.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 5.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 5.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 5.4,
        name: "Moon 4",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 5.5,
        name: "Moon 5",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 5.6,
        name: "Moon 6",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
    ],
  },
  {
    id: 6,
    name: "Saturn",
    type: "Terrestrial",
    category: "Planet",
    moons: [
      {
        id: 6.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 6.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 6.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
    ],
  },
  {
    id: 7,
    name: "Uranus",
    type: "Ice Giant",
    category: "Planet",
    moons: [
      {
        id: 7.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 7.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 7.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
    ],
  },
  {
    id: 8,
    name: "Neptune",
    type: "Ice Giant",
    category: "Planet",
    moons: [
      {
        id: 8.1,
        name: "Moon 1",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 8.2,
        name: "Moon 2",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
      {
        id: 8.3,
        name: "Moon 3",
        nameHistory: "History of the name of this moon",
        size: "Small",
        category: "Moon",
      },
    ],
  },
  {
    id: 9,
    name: "Pluto",
    type: "Dwarf Planet",
    category: "Planet"
  }
];

export default planets;